image: golang:1.11

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test

unit_tests:
  image: docker
  services:
    - docker:dind
  stage: test
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - ./scripts/run.sh etl make test-internal

lint_code:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint-verbose
