image: golang/alpine

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test

unit_tests:
  image: tmaier/docker-compose:latest
  stage: test
  services:
    - docker:dind
  tags:
    - docker
  script:
    - ./scripts/run.sh etl go test ./...

lint_code:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint-verbose
