image: golang/alpine

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test

unit_tests:
  image: docker/compose:1.25.0-rc2-alpine
  stage: test
  variables:
    GOPATH: "~"
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - echo $GOPATH
  script:
    - ./scripts/run.sh etl go test ./...

lint_code:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint-verbose
