cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test
  - deploy

unit:
  image: docker/compose:1.25.0-rc2-alpine
  stage: test
  variables:
    GOPATH: "~"
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - echo $GOPATH
  script:
    - make test

lint:
  image: golangci/golangci-lint
  before_script:
    - apk update
    - apk add make
  stage: test
  script:
    - make lint-verbose

deploy:develop:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
  except:
    - schedules
  environment:
    name: develop
  script: make -C ./build deploy
  only:
    - master

deploy:staging:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
  environment:
    name: staging
  script: make -C ./build deploy
  only:
    - schedules

deploy:production:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
  environment:
    name: production
  script: make -C ./build deploy
  only:
    - master
  when: manual
