image: tmaier/docker-compose:latest

services:
  - docker:dind

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  - docker info
  - docker-compose --version

stages:
  - test

unit_tests:
  stage: test
  tags:
    - docker
  script:
    - ./scripts/run.sh etl make test-internal

lint_code:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint-verbose
