cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test
  - build
  - smoke-test
  - deploy

unit:
  image: docker/compose:1.25.0-rc2-alpine
  stage: test
  except:
    - master
  variables:
    GOPATH: "~"
  services:
    - docker:19.03.5-dind
  tags:
    - docker
  before_script:
    - echo $GOPATH
    - apk update
    - apk add make curl bash
  script:
    - make test

lint:
  image: golangci/golangci-lint
  stage: test
  except:
    - master
  script:
    - make lint-verbose

build:
  stage: build
  image: docker:stable
  except:
    - master
  services:
    - docker:19.03.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
  environment:
    name: develop
  script: make docker-build

smoke-test:
  stage: smoke-test
  image: docker/compose:alpine-1.25.4
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  artifacts:
    when: on_failure
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./logs/
  before_script:
    - apk update
    - apk add make git jq curl
    - make docker-gitlab-build
    - git clone --single-branch -b $CI_COMMIT_BRANCH https://gitlab.com/thorchain/thornode.git || git clone --single-branch -b master https://gitlab.com/thorchain/thornode.git
    - cd thornode
    - test master = $(git rev-parse --abbrev-ref HEAD) && docker pull registry.gitlab.com/thorchain/thornode:mocknet
    - make -C build/docker reset-mocknet-standalone
  except:
    - schedules
  environment:
    name: development
  script:
    - git clone --single-branch -b $CI_COMMIT_BRANCH https://gitlab.com/thorchain/heimdall.git || git clone --single-branch -b master https://gitlab.com/thorchain/heimdall.git
    - cd ./heimdall
    - make build
    - make smoke
  after_script:
    - ./scripts/docker_logs.sh

# Build docker image
build-gitlab-docker:
  stage: build
  image: docker:stable
  only:
    - master
  services:
    - docker:19.03.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git jq curl
    - make docker-gitlab-login
  script:
    - make docker-gitlab-build
    - make docker-gitlab-push

deploy:develop:
  stage: deploy
  image: docker:stable
  services:
    - docker:19.03.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
  except:
    - schedules
  environment:
    name: develop
  script: make docker-deploy
  only:
    - master

deploy:staging:
  stage: deploy
  image: docker:stable
  services:
    - docker:19.03.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
  environment:
    name: staging
  script: make docker-deploy
  only:
    - schedules

deploy:production:
  stage: deploy
  image: docker:stable
  services:
    - docker:19.03.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk update
    - apk add python py-pip make git
    - pip install awscli
  environment:
    name: production
  script: make docker-deploy
  only:
    - master
  when: manual
