image: golang:1.11

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test

unit_tests:
  image: 
    name: docker/compose:1.25.0-rc2-alpine
    entrypoint: ["/bin/sh", "-c"]
  services:
    - docker:dind
  stage: test
  before_script:
    - docker version
    - docker-compose version
  script:
    - ./scripts/run.sh etl make test-internal

lint_code:
  image: golangci/golangci-lint
  stage: test
  script:
    - make lint-verbose
