image: golang/alpine

cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test
  - deploy

unit_tests:
  image: docker/compose:1.25.0-rc2-alpine
  stage: test
  variables:
    GOPATH: "~"
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - echo $GOPATH
  script:
    - ./scripts/run.sh chain-service go test ./...

# TODO This is broker for some reason and blocking the cicd pipline.
#lint_code:
#  image: golangci/golangci-lint
#  stage: test
#  script:
#    - make lint-verbose

trigger_build_and_deploy:
  stage: deploy
  only:
    - master
  script:
    - "curl -X POST -F token=$TOKEN -F ref=master https://gitlab.com/api/v4/projects/14289231/trigger/pipeline"
