development:
  dialect: postgres
  datasource: host=127.0.0.1 dbname=midgard user=midgard password=password sslmode=disable
  dir: ./db/migrations
  table: migrations

test:
  dialect: postgres
  datasource: host=127.0.0.1 dbname=midgard_test user=postgres password=password sslmode=disable
  dir: ./db/migrations
  table: migrations
