version: '3'

services:
  midgard:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
      args:
        thornode_host: thormock:8081
        pg_host: pg
    image: midgard
    ports:
      - 8080:8080
    links:
      - pg
    depends_on:
      - pg
  pg:
    image: timescale/timescaledb:latest-pg11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  thormock:
    build:
      context: ./tools/mockServer
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081

