version: '3'

services:
  chain-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        chain_host: $CHAIN_HOST
    image: bepswap-chain-service
    ports:
      - 8080:8080
    links:
      - pg
    depends_on:
      - pg
    volumes:
      - ${GOPATH}:/root/go
      - .:/root/go/src/gitlab.com/thorchain/bepswap/chain-service
    working_dir: /root/go/src/gitlab.com/thorchain/bepswap/chain-service
    command: make install run-in-docker
    environment:
      GOPATH: /root/go
      GOBIN: /root/go/bin
      GO111MODULE: "on"
  pg:
    image: timescale/timescaledb:latest-pg11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
