openapi: 3.0.0
info:
  contact:
    email: devs@thorchain.org
  description: Chain-Service Public API
  title: Chain-Service Public API
  version: 1.0.0-oas3
paths:
  "/v1/doc":
    get:
      operationId: GetDocs
      responses:
        "200":
          description: swagger/openapi 3.0 spec generated docs
      summary: This swagger/openapi 3.0 generated documentation
      tags:
        - Documentation
  "/v1/graphql":
    get:
      operationId: GetGraphqlPlayground
      responses:
        "200":
          description: GraphQL playground
  "/v1/graphql/query":
    post:
      operationId: PostGraphqlQuery
      responses:
        "200":
          description: GraphQL playground
  "/v1/health":
    get:
      operationId: GetHealth
      responses:
        "200":
          description: Get Health responce of API
  "/v1/poolData":
    get:
      operationId: GetPoolData
      parameters:
        - in: query
          name: asset
          description: Get Specify asset Pool Data
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Asset pool information
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/PoolData"
  "/v1/stakerData":
    get:
      parameters:
        - in: query
          name: staker
          description: staker address
          required: true
          schema:
            type: string
        - in: query
          name: asset
          description: Specify asset
          required: false
          schema:
            type: string
      operationId: GetStakerData
      responses:
        "200":
          description: Get Staker info Data from API
          content:
            application/json:
              schema:
                oneOf:
                  - "$ref": "#/components/schemas/StakerInfo"
                  - "$ref": "#/components/schemas/StakerInfoWithAsset"
  "/v1/stakerTx":
    get:
      operationId: GetStakerTx
      parameters:
        - in: query
          name: staker
          description: Staker address
          required: true
          schema:
            type: string
        - in: query
          name: limit
          description: limit results returned default 25
          required: false
          schema:
            type: integer
        - in: query
          name: offset
          description: offset ... default to 0
          required: false
          schema:
            type: integer
        - in: query
          name: asset
          description: Specify asset
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Get Staker transaction Data from API
  "/v1/swagger.json":
    get:
      operationId: GetSwagger
      responses:
        "200":
          description: human and machine readable swagger/openapi specification endpoint
      summary: JSON swagger/openapi 3.0 specification endpoint
      tags:
        - Specification
  "/v1/swapData":
    get:
      operationId: GetSwapData
      parameters:
        - in: query
          name: asset
          description: Specify asset
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Swap data information
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SwapData"
  "/v1/swapTx":
    get:
      operationId: GetSwapTx
      parameters:
        - in: query
          name: asset
          description: asset
          required: true
          schema:
            type: string
        - in: query
          name: sender
          description: sender address
          required: true
          schema:
            type: string
        - in: query
          name: dest
          description: dest address
          required: true
          schema:
            type: string
        - in: query
          name: limit
          description: limit results returned. Default 25
          required: false
          schema:
            type: integer
        - in: query
          name: offset
          description: Offset. Default to 0
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: Get Swap transaction Data from API
  "/v1/tokenData":
    get:
      parameters:
        - in: query
          name: symbol
          description: Specify symbol
          required: true
          schema:
            type: string
      operationId: GetTokenData
      responses:
        "200":
          description: Get Token Data from API
  "/v1/assets":
    get:
      description: Returns an array containing all the assets supported.
      parameters:
        - in: query
          name: asset
          description: Specify asset
          required: false
          schema:
            type: string
            example: BNB.TOMOB-1E1 or TOMOB-1E1
      operationId: GetAssets
      responses:
        "200":
          description: Get Tokens from API
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  "$ref": "#/components/schemas/Asset"
  "/v1/tradeData":
    get:
      parameters:
        - in: query
          name: symbol
          description: symbol
          required: true
          schema:
            type: string
      operationId: GetTradeData
      responses:
        "200":
          description: Get Trade Data from API
  "/v1/userData":
    get:
      operationId: GetUserData
      responses:
        "200":
          description: Get User Data from API
components:
  schemas:
    Asset:
      type: object
      properties:
        chain:
          type: string
        symbol:
          type: string
        ticker:
          type: string
    TokenList:
      type: array
      items:
        type: string
    TokenData:
      type: object
      properties:
        symbol:
          type: string
        ticker:
          type: string
        price:
          type: number
      required:
        - symbol
        - ticker
        - price
    SwapData:
      type: object
      properties:
        asset:
          type: string
        aveTxTkn:
          type: number
        aveTxRune:
          type: number
        aveSlipTkn:
          type: number
        aveSlipRune:
          type: number
        numTxTkn:
          type: number
        numTxRune:
          type: number
        aveFeeTkn:
          type: number
        aveFeeRune:
          type: number
      required:
        - asset
        - aveTxTkn
        - aveTxRune
        - aveSlipTkn
        - aveSlipRune
        - numTxTkn
        - numTxRune
        - aveFeeTkn
        - aveFeeRune
    StakerInfo:
      type: object
      properties:
        address:
          type: string
        asset:
          type: string
        dateFirstStaked:
          type: string
        runeEarned:
          type: number
        runeStaked:
          type: number
        tokensEarned:
          type: number
        tokensStaked:
          type: number
        units:
          type: number
      required:
        - address
        - asset
        - dateFirstStaked
        - runeEarned
        - runeStaked
        - tokensEarned
        - tokensStaked
        - units
    StakerInfoWithAsset:
      type: array
      items:
        type: string
    PoolData:
      type: object
      properties:
        asset:
          type: string
        totalFeesTKN:
          type: number
        totalFeesRune:
          type: number
        vol24hr:
          type: number
        volAT:
          type: number
        depth:
          type: number
        poolUnits:
          type: number
        roiAT:
          type: number
        roi30:
          type: number
        roi12:
          type: number
        numStakers:
          type: number
        numStakeTx:
          type: number
        numSwaps:
          type: number
      required:
        - asset
        - totalFeesTKN
        - totalFeesRune
        - vol24hr
        - volAT
        - depth
        - poolUnits
        - roiAT
        - roi30
        - roi12
        - numStakers
        - numStakeTx
        - numSwaps
servers:
  - url: http://127.0.0.1:8080
  - url: https://127.0.0.1:8080
tags:
  - description: Public Bepswap Chain-Service's REST API
    name: Chain-Service Public API
